kind: ConfigMap
apiVersion: v1
metadata:
  name: vault-config
  namespace: default
data:
  vault.hcl: |
    disable_cache = true
    disable_mlock = true
    
    ui = true
    api_addr = "http://127.0.0.1"
    
    listener "tcp" {
      address 	= "127.0.0.1:8200"
      tls_disable = 1
    }
    
    storage "consul" {
      address = "127.0.0.1:8500"
      path    = "mycompany/"
      disable_registration = "true"
    }
    
    max_lease_ttl = "10h"
    default_lease_ttl = "10h"
    raw_storage_endpoint = true
    cluster_name = "mycompany-vault"