
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: juice-shop-oppa
  labels:
    app: juice-shop-oppa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juice-shop-oppa
  template:
    metadata:
      labels:
        app: juice-shop-oppa
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim
      containers:
      - name: juice-shop-oppa
        image: "bkimminich/juice-shop:latest"
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: "/var/log/challenge1"
          name: task-pv-storage
              